name: VSIX

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Version
      run: ((Get-Content -Path source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path source.extension.vsixmanifest
      working-directory: VSIXProjectSample
      shell: pwsh

    - name: Restore
      run: dotnet restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild /t:Rebuild

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          **/*.vsix
